# Generated by Django 3.2.8 on 2021-10-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('img_url', models.URLField(verbose_name='آدرس تصویر')),
                ('link', models.URLField(verbose_name='لینک')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='تعداد کلیک')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد نمایش')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='advertiser_management.advertiser', verbose_name='تبلیغ کننده')),
            ],
        ),
    ]
