# Generated by Django 3.2.8 on 2021-10-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_type', models.CharField(choices=[('HOURLY', 'ساعتی'), ('DAILY', 'روزانه')], max_length=50, verbose_name='تایپ زمانی')),
                ('from_date', models.DateTimeField(verbose_name='از تاریخ')),
                ('total_clicks', models.PositiveIntegerField(verbose_name='مجموع تعداد کلیک ها')),
                ('total_views', models.PositiveIntegerField(verbose_name='مجموع تعداد نمایش ها')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzes', to='advertiser_management.ad', verbose_name='تبلیغ')),
            ],
            options={
                'verbose_name': 'آنالیز تبلیغ',
                'verbose_name_plural': 'آنالیز تبلیغات',
            },
        ),
    ]
