# Generated by Django 3.2.8 on 2021-10-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_auto_20211007_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='delay',
            field=models.DurationField(null=True, verbose_name='اختلاف زمان نمایش و کلیک'),
        ),
    ]
